Вариант 7

In [1]:
import copy
import numpy as np
from sympy.combinatorics import Permutation
import math
Permutation.print_cyclic = False

In [4]:
n = int(input("Vvedite poryadok sistemy "))

Vvedite poryadok sistemy 4


In [5]:
print("Vvedite sistemu srazu s pravoi chastyu")
matrix=[]
for i in range(n):
    matrix.append(list(map(float,input().split())))
matrix=np.array(matrix)

Vvedite sistemu srazu s pravoi chastyu
0.78 -0.02 -0.12 -0.14 0.76
-0.02 0.86 -0.04 0.06 0.08
-0.12 -0.04 0.72 -0.08 1.12
-0.14 0.06 -0.08 0.74 0.68


In [3]:
'''

10 -2 -2 6
-1 10 -2 7
-1 -1 10 8



2 3 -1 9
1 -2 1 3
1 0 2 2
'''

'''
1 0.4 0.2 0.6
0.5 0.8 0.2 0.7
0 0.8 1 1.4
'''


'''
0.78 -0.02 -0.12 -0.14 0.76
-0.02 0.86 -0.04 0.06 0.08
-0.12 -0.04 0.72 -0.08 1.12
-0.14 0.06 -0.08 0.74 0.68




'''


'\n1 0.4 0.2 0.6\n0.5 0.8 0.2 0.7\n0 0.8 1 1.4\n'

In [6]:
def gauss_method(matrix,n=n):
    #matrix.dtype=np.float
    perm_list=[]
    matrix=matrix.astype("float64")
    m=len(matrix[0])
    for i in range(n):
        sort_a=matrix[0:n,i:n]
        perm=sort_a[i].argsort()[::-1]
        sort_a=sort_a[:,perm]
        perm+=i
        perm=np.concatenate((np.array(range(n-len(perm))),perm))
        perm_list.append(perm)
        matrix[0:n,i:n]=sort_a
        tmp=matrix[i][i]
        for j in range(i,m):
            matrix[i][j]/=tmp
        for j in range(i+1,n):
            matrix[j]-=(matrix[i]*matrix[j][i])  
    for i in range(n-1,-1,-1):
        if (matrix[i][i]):
            for j in range(i-1,-1,-1):
                matrix[j]-=(matrix[i]*matrix[j][i])
    return matrix,perm_list

In [7]:
equations=copy.deepcopy(matrix)
#equations=np.concatenate((equations,b),axis=1)
equations,perm_list=gauss_method(equations)
if (perm_list is  None):
    answer=equations[0:n,-1]
else:
    id_p=Permutation(range (n))
    for perm in perm_list:
        id_p=id_p*Permutation(perm)
    answer=(equations[0:n,-1])[((id_p).array_form)]
print(answer)



[1.53496503 0.12200957 1.97515642 1.41295547]


In [8]:
A = matrix[0:n,0:n]
b = matrix[0:n,n]
D = np.zeros((n,n))
D_invert = np.zeros((n,n))
L = np.zeros((n,n))
R = np.zeros((n,n))
for i in range (n):
    D[i][i] = A[i][i]
    D_invert[i][i] = 1/A[i][i]
    for j in range (n):
        if (j<i):
            L[i][j] = A[i][j]
        elif (j>i):
            R[i][j] = A[i][j]

H = np.identity(n) - D_invert@A
g = D_invert@b

In [9]:
H,g

(array([[ 0.00000000e+00,  2.56410256e-02,  1.53846154e-01,
          1.79487179e-01],
        [ 2.32558140e-02,  0.00000000e+00,  4.65116279e-02,
         -6.97674419e-02],
        [ 1.66666667e-01,  5.55555556e-02,  1.11022302e-16,
          1.11111111e-01],
        [ 1.89189189e-01, -8.10810811e-02,  1.08108108e-01,
          0.00000000e+00]]),
 array([0.97435897, 0.09302326, 1.55555556, 0.91891892]))

In [10]:
np.linalg.norm(H,float("inf"))

0.3783783783783784

In [11]:
K=7
def iterate_method(H,g,k=K,n=n):
    output = np.zeros(n)
    x_prev=None
    for i in range(k):
        x_prev=output
        output = H@x_prev+g
    return output,x_prev

In [12]:
iterate_answer, x_prev = iterate_method(H,g)

In [13]:
iterate_answer

array([1.53454378, 0.1220109 , 1.97478423, 1.4125631 ])

In [14]:
x_prev

array([1.5335941 , 0.12201245, 1.9739283 , 1.41166072])

In [15]:
answer

array([1.53496503, 0.12200957, 1.97515642, 1.41295547])

In [16]:
def spec_radius(input):
    radius = max(np.absolute(np.linalg.eigvals(input)))
    return radius

def apr_eval(H=H,g=g,k=K):
    return np.linalg.norm(H)**k/(1-np.linalg.norm(H,float("inf")))*np.linalg.norm(g,float("inf"))

def apostr_eval(x_k,x_prev,H=H,g=g):
    return np.linalg.norm(H)/(1-np.linalg.norm(H,float("inf")))*np.linalg.norm(x_k-x_prev,float("inf"))

def lust(x_k,x_prev,H=H):
    radius = spec_radius(H)
    return x_k + radius/(1-radius) * (x_k-x_prev)
    

In [17]:
apr_eval()

0.004224821326595804

In [18]:
apostr_eval(iterate_answer,x_prev)

0.0006137239321379526

In [19]:
np.linalg.norm(answer-iterate_answer,float("inf"))

0.0004212583334346487

In [20]:
lust_answer=lust(iterate_answer,x_prev)

In [21]:
lust_answer

array([1.53495994, 0.12201022, 1.97515932, 1.41295853])

In [22]:
np.linalg.norm(answer-lust_answer,float("inf"))

5.092872696454975e-06

In [48]:
H_L = -D_invert@L
H_R = -D_invert@R

def seid(k=7,matrix=matrix,g=g,H_R=H_R, H_L=H_L,n=n):
    x_next=np.zeros(n)
    
    for t in range(k):
        x_prev=x_next
        #x_next=g[i]+x_next@H_L + x_prev@H_R
        #x_next = np.linalg.inv(np.identity(n)-H_L)@H_R@x_prev+np.linalg.inv(np.identity(n)-H_L)@g
    
        for i in range(n):
            comp = g[i] 
            comp+=H_L[i]@x_next
            comp += H_R[i]@x_prev
    
            x_next[i]=comp
            
    return x_next
    

In [49]:
answer

array([1.53496503, 0.12200957, 1.97515642, 1.41295547])

In [50]:
seid_answer = seid()

In [51]:
seid_answer

array([1.53496422, 0.12200953, 1.97515609, 1.41295528])

In [52]:
np.linalg.norm(answer-seid_answer,float("inf"))

8.19413846553374e-07

In [53]:
H_seid = -(np.linalg.inv(D+L))@R

In [54]:
radius_seid = spec_radius(H_seid)

In [55]:
radius_seid

0.10568959696378756

In [56]:
def rel(matrix = matrix, H=H, n=n, k=7):
    q_opt = 2/(1+math.sqrt(1-spec_radius(H)**2))
    A = matrix[:,:n]
    b = matrix[:,n:n+1]
    x_next=np.zeros(n)
    for i in range(k):
        x_prev= x_next
        for j in range(n):
            x_next[j] = x_prev[j] + q_opt*(b[j] - (x_next[0:j]@A[j,0:j] + 
                                           x_prev[j:n]@A[j,j:n]))/A[j][j]
            
    return x_next
    
    
    

In [57]:
rel_answer = rel()

In [58]:
rel_answer

array([1.53496501, 0.12200957, 1.97515641, 1.41295546])

In [34]:
rel_answer - answer



array([-2.95513845e-08, -2.23537892e-09, -9.97129135e-09, -4.75405670e-09])

In [35]:
np.linalg.norm(rel_answer-answer,float("inf"))

2.9551384450599016e-08