In [1]:
import numpy as np

<img src="img_3.png">

In [2]:
A = np.array([[-125, 123.35 ],[123.35, -123]])

In [3]:
h = 0.1

In [4]:
values, vectors = np.linalg.eig(A)

In [5]:
values

array([-247.35405344,   -0.64594656])

In [6]:
vectors

array([[-0.70996716, -0.70423478],
       [ 0.70423478, -0.70996716]])

In [7]:
c1, c2 = np.linalg.solve(vectors, np.array([1,1]))
print(c1, c2)

-0.0057323822805923075 -1.414201944487911


In [8]:
y_true = lambda x: (c1 * vectors[:,0]*np.exp(values[0]*x) + c2 * vectors[:,1]*np.exp(values[1]*x)).reshape(2,1)

In [9]:
y_true(0)

array([[1.],
       [1.]])

In [10]:
for i in range(0, 6):
    print (y_true(h*i).T)

[[1. 1.]]
[[0.93363215 0.9412318 ]]
[[0.87523101 0.88235528]]
[[0.82048301 0.82716164]]
[[0.76915964 0.77542051]]
[[0.72104669 0.72691592]]


In [11]:
y_eu = np.array([[1],[1]])
y_eu_true = np.array([[1],[1]])

In [12]:
for i in range(1, 6):

    W = np.identity(2) + A*h
    y_next = (W@y_eu[:,i-1]).reshape(2,1)
    y_eu = np.concatenate((y_eu, y_next), 1)
    y_eu_true = np.concatenate((y_eu_true, y_true(h*i)),1)


In [13]:
y_eu.T

array([[ 1.00000000e+00,  1.00000000e+00],
       [ 8.35000000e-01,  1.03500000e+00],
       [ 3.16422500e+00, -1.39577500e+00],
       [-5.36054721e+01,  5.48029729e+01],
       [ 1.29245760e+03, -1.28049709e+03],
       [-3.06581940e+04,  3.04120816e+04]])

In [14]:
np.max(abs(y_eu-y_eu_true))

30658.91507663389

In [15]:
y_inv = np.array([[1],[1]])
y_inv_true = np.array([[1],[1]])

In [16]:
for i in range(1, 6):
    W = np.linalg.inv((np.identity(2) - A*h))
    y_next = (W@y_inv[:,i-1]).reshape(2,1)
    y_inv = np.concatenate((y_inv, y_next), 1)
    y_inv_true = np.concatenate((y_inv_true, y_true(h*i)),1)

In [17]:
y_inv.T

array([[1.        , 1.        ],
       [0.93565992, 0.94295978],
       [0.87874603, 0.88588662],
       [0.82542227, 0.83214062],
       [0.77533927, 0.78165041],
       [0.72829527, 0.7342235 ]])

In [18]:
np.max(abs(y_inv - y_inv_true))

0.007307586392413912

In [19]:
y_inter_3 = np.array([[1],[1]])
y_inter_3_true = np.array([[1],[1]])
W = np.linalg.inv((np.identity(2) - A*h))
y_next = (W@y_inter_3[:,0]).reshape(2,1)
y_inter_3 = np.concatenate((y_inter_3, y_next), 1)
y_inter_3_true = np.concatenate((y_inter_3_true, y_true(h)),1)

In [20]:
for i in range(2, 6):
    W_0 = (np.identity(2)+2/3*h*A)@np.linalg.inv((np.identity(2)-5/12*h*A))
    W_1 = (h/12*A)@np.linalg.inv((np.identity(2)-5/12*h*A))
    y_next = (W_0@y_inter_3[:,i-1] - W_1@y_inter_3[:,i-2]).reshape(2,1)
    y_inter_3 = np.concatenate((y_inter_3, y_next), 1)
    y_inter_3_true = np.concatenate((y_inter_3_true, y_true(h*i)),1)

In [21]:
y_inter_3.T

array([[1.        , 1.        ],
       [0.93565992, 0.94295978],
       [0.8774992 , 0.88359128],
       [0.82142667, 0.82949476],
       [0.77173479, 0.77593197],
       [0.72093027, 0.72990651]])

In [22]:
np.max(abs(y_inter_3-y_inter_3_true))

0.002990595088570802

In [23]:
6/ max(abs(values))

0.024256728024322063

In [24]:
2/ max(abs(values))

0.008085576008107356

In [25]:
h = 0.001

In [26]:
y_eu = np.array([[1],[1]])
y_eu_true = np.array([[1],[1]])
for i in range(1, 501):

    W = np.identity(2) + A*h
    y_next = (W@y_eu[:,i-1]).reshape(2,1)
    y_eu = np.concatenate((y_eu, y_next), 1)
    y_eu_true = np.concatenate((y_eu_true, y_true(h*i)),1)


In [27]:
np.max(abs(y_eu-y_eu_true))

0.00020797702897090709

In [28]:
y_inv = np.array([[1], [1]])
y_inv_true = np.array([[1], [1]])
for i in range(1, 501):
    W = np.linalg.inv((np.identity(2) - A * h))
    y_next = (W @ y_inv[:, i - 1]).reshape(2, 1)
    y_inv = np.concatenate((y_inv, y_next), 1)
    y_inv_true = np.concatenate((y_inv_true, y_true(h * i)), 1)


In [29]:
np.max(abs(y_inv-y_inv_true))

0.0001688823697275632

In [30]:
h = 0.001
y_inter_3 = np.array([[1], [1]])
y_inter_3_true = np.array([[1], [1]])
W = np.linalg.inv((np.identity(2) - A * h))
y_next = (W @ y_inter_3[:, 0]).reshape(2, 1)
y_inter_3 = np.concatenate((y_inter_3, y_next), 1)
y_inter_3_true = np.concatenate((y_inter_3_true, y_true(h)), 1)
for i in range(2, 501):
    W_0 = (np.identity(2) + 2 / 3 * h * A) @ np.linalg.inv((np.identity(2) - 5 / 12 * h * A))
    W_1 = (h / 12 * A) @ np.linalg.inv((np.identity(2) - 5 / 12 * h * A))
    y_next = (W_0 @ y_inter_3[:, i - 1] - W_1 @ y_inter_3[:, i - 2]).reshape(2, 1)
    y_inter_3 = np.concatenate((y_inter_3, y_next), 1)
    y_inter_3_true = np.concatenate((y_inter_3_true, y_true(h * i)), 1)

In [31]:
np.max(abs(y_inter_3 - y_inter_3_true))

8.4993032189562e-05

In [32]:
y_extr_2 = np.array([[1], [1]])
y_extr_2_true  = np.array([[1], [1]])
W = np.linalg.inv((np.identity(2) - A * h))
y_next = (W @ y_extr_2[:, 0]).reshape(2, 1)
y_extr_2 = np.concatenate((y_extr_2, y_next), 1)
y_extr_2_true = np.concatenate((y_extr_2_true, y_true(h)), 1)
for i in range(2, 501):
    W_0 = np.identity(2)+(3/2*h*A)
    W_1 = h/2*A
    y_next = (W_0@y_extr_2[:,i-1] - W_1@y_extr_2[:,i-2]).reshape(2,1)
    y_extr_2 = np.concatenate((y_extr_2, y_next), 1)
    y_extr_2_true = np.concatenate((y_extr_2_true, y_true(h * i)), 1)

In [33]:
np.max(abs(y_extr_2 - y_extr_2_true))

8.4993032189562e-05